/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package javaalgorithms;

import java.util.Scanner;

public class App {
    
    public static void main(String[] args) {
        var maxInputLength = 255;
        String userInput = null;
        Scanner scanner = new Scanner(System.in);
        while (true)
        {
            System.out.println("Please enter a string up to " + maxInputLength + " characters in length.  Numbers, spaces, and alpha characters are ok.\r\n");
            
            userInput = scanner.nextLine();

            // Check if input exceeds maximum length
            if (userInput.length() > maxInputLength) {
                System.out.println("\r\nInput exceeds maximum length of " + maxInputLength + " characters.");
                // Truncate input to maximum length
                userInput = userInput.substring(0, maxInputLength);
                System.out.println("\r\nTruncated string: " + userInput + "\r\n");
            }

            if (userInput.isEmpty())
            {
                System.out.println("Thank you, bye.");
                break;
            }
            else
            {
                System.out.println("\r\nUser input: \"" + userInput +"\"");
                var inputLength = userInput.length();
                System.out.println("\r\nNumber of characters: " + inputLength);
                System.out.println("\r\nNumber of vowels: " + CountVowels(userInput));
            }
        }
        scanner.close();
    }

    private static int CountVowels(String sampleString)
    {
        int vowelCount = 0;

        if (!sampleString.isEmpty())
        {
            var vowels = new char[]
            {
                'a', 'e', 'i', 'o', 'u'
            };
            String lowerCaseString = sampleString.toLowerCase();
            char[] characters = lowerCaseString.toCharArray();
            var j = (characters.length / 2) + 1;
            for (int i = characters.length / 2; i >= 0; i--)
            {
                for(char vowel: vowels)
                {
                    if (j < characters.length && vowel == characters[j])
                    {
                        vowelCount += 1;
                    }
                    if (vowel == characters[i])
                    {
                        vowelCount += 1;
                    }
                }
                j++;
            }
        }
        return vowelCount;
    }
}
